services:
  - type: web
    name: recipe-archive-backend
    env: java
    rootDir: ./
    buildCommand: ./mvnw clean package -DskipTests
    startCommand: java -jar target/*.jar
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: recipe-archive-db
          property: connectionString
  - type: web
    name: recipearchive-frontend
    env: static
    rootDir: frontend
    buildCommand: npm install && npm run build
    staticPublishPath: build
    envVars:
      - key: PUBLIC_API_URL
        value: https://recipe-archive-backend.onrender.com
databases:
  - name: recipe-archive-db
    plan: free
    databaseName: recipe_db